/* Generated By:JJTree: Do not edit this line. ASTAddAssign.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTAddAssign extends ASTAddNode {
    public ASTAddAssign(int id) {
	super(id);
    }

    public ASTAddAssign(Parser p, int id) {
	super(p, id);
    }

    public static Node jjtCreate(int id) {
	return new ASTAddAssign(id);
    }

    public static Node jjtCreate(Parser p, int id) {
	return new ASTAddAssign(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	SimpleNode lhs = (SimpleNode) jjtGetChild(0);
	Object val = super.evaluate(demi);
	return assign(demi, lhs, val);
    }
}
