/* Generated By:JJTree: Do not edit this line. ASTArgumentList.java */

package JP.ac.osaka_u.shugo.demi;

import java.util.*;

public class ASTArgumentList extends SimpleNode {
    public ASTArgumentList(int id) {
	super(id);
    }

    public ASTArgumentList(Parser p, int id) {
	super(p, id);
    }

    public Object[] getArguments(Demi demi) throws Throwable {
	Vector args = new Vector();
	for (int i = 0; i < jjtGetNumChildren(); i++) {
	    args.addElement(((SimpleNode) jjtGetChild(i)).evaluate(demi));
	}
	Object[] result = new Object[args.size()];
	args.copyInto(result);
	return result;
    }
}
