/* Generated By:JJTree: Do not edit this line. ASTAssignment.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTAssignment extends SimpleNode {
    public ASTAssignment(int id) {
	super(id);
    }

    public ASTAssignment(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	SimpleNode lhs = (SimpleNode) jjtGetChild(0);
	Object val = ((SimpleNode) jjtGetChild(1)).evaluate(demi);
	return assign(demi, lhs, val);
    }
}
