/* Generated By:JJTree: Do not edit this line. ASTBreak.java */

package JP.ac.osaka_u.shugo.demi;

import java.util.Stack;

public class ASTBreak extends SimpleNode {

    public ASTBreak(int id) {
	super(id);
    }

    public ASTBreak(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws Break {
	Stack stack = demi.getCallInfoStack();
	if (stack != null)
	    stack = (Stack) stack.clone();
	throw new Break(this, stack, demi.getScope());
    }
}
