/* Generated By:JJTree: Do not edit this line. ASTBitwiseComplNode.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTBitwiseComplNode extends SimpleNode {
    public ASTBitwiseComplNode(int id) {
	super(id);
    }

    public ASTBitwiseComplNode(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	Object obj = ((SimpleNode) jjtGetChild(0)).evaluate(demi);
	if (obj instanceof Number)
	    return Numeric.not((Number) obj);
	throw new IllegalArgumentException(
			 "illegal argument " + obj + " for ~");
    }
}
