/* Generated By:JJTree: Do not edit this line. ASTBooleanLiteral.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTBooleanLiteral extends LiteralNode {
  public ASTBooleanLiteral(int id) {
    super(id);
  }

  public ASTBooleanLiteral(Parser p, int id) {
    super(p, id);
  }

}
