/* Generated By:JJTree: Do not edit this line. ASTBitwiseOrNode.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTBitwiseOrNode extends SimpleNode {
    public ASTBitwiseOrNode(int id) {
	super(id);
    }

    public ASTBitwiseOrNode(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	Object left = ((SimpleNode) jjtGetChild(0)).evaluate(demi);
	Object right = ((SimpleNode) jjtGetChild(1)).evaluate(demi);
	if (left instanceof Number && right instanceof Number)
	    return Numeric.or((Number) left, (Number) right);
	throw new IllegalArgumentException("illegal arguments " +
					   left + ", " + right +
					   " for |");
    }
}
