/* Generated By:JJTree: Do not edit this line. ASTCharacterLiteral.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTCharacterLiteral extends LiteralNode {
  public ASTCharacterLiteral(int id) {
    super(id);
  }

  public ASTCharacterLiteral(Parser p, int id) {
    super(p, id);
  }

}
