/* Generated By:JJTree: Do not edit this line. ASTClosure.java */

package JP.ac.osaka_u.shugo.demi;

import java.util.*;

public class ASTClosure extends SimpleNode {

    Vector args = new Vector();

    public ASTClosure(int id) {
	super(id);
    }

    public ASTClosure(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) {
	Symbol[] argumentList = new Symbol[args.size()];
	args.copyInto(argumentList);
	SimpleNode body = (SimpleNode) jjtGetChild(0);
	return new Closure(demi, argumentList, body, demi.getScope());
    }
}
