/* Generated By:JJTree: Do not edit this line. ASTClassExpression.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTClassExpression extends SimpleNode {

    String name;
    
    public ASTClassExpression(int id) {
	super(id);
    }

    public ASTClassExpression(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws ClassNotFoundException {
	Class cls = Class.forName(name);
	return cls;
    }
}
