/* Generated By:JJTree: Do not edit this line. ASTContinue.java */

package JP.ac.osaka_u.shugo.demi;

import java.util.Stack;

public class ASTContinue extends SimpleNode {

    public ASTContinue(int id) {
	super(id);
    }
    
    public ASTContinue(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws Continue {
	Stack stack = demi.getCallInfoStack();
	if (stack != null)
	    stack = (Stack) stack.clone();
	throw new Continue(this, stack, demi.getScope());
    }
}
