/* Generated By:JJTree: Do not edit this line. ASTExpressionList.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTExpressionList extends SimpleNode {
    public ASTExpressionList(int id) {
	super(id);
    }

    public ASTExpressionList(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	Object result = null;
	for (int i = 0; i < jjtGetNumChildren(); i++) {
	    result = ((SimpleNode) jjtGetChild(i)).evaluate(demi);
	}
	return result;
    }
}
