/* Generated By:JJTree: Do not edit this line. ASTFloatLiteral.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTFloatLiteral extends LiteralNode {
  public ASTFloatLiteral(int id) {
    super(id);
  }

  public ASTFloatLiteral(Parser p, int id) {
    super(p, id);
  }

}
