/* Generated By:JJTree: Do not edit this line. ASTHashExpression.java */

package JP.ac.osaka_u.shugo.demi;

import java.util.*;

public class ASTHashExpression extends SimpleNode {
    public ASTHashExpression(int id) {
	super(id);
    }

    public ASTHashExpression(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	Hashtable tbl = new Hashtable();
	for (int i = 0; i < jjtGetNumChildren(); i += 2) {
	    Object key = ((SimpleNode) jjtGetChild(i)).evaluate(demi);
	    Object val = ((SimpleNode) jjtGetChild(i + 1)).evaluate(demi);
	    tbl.put(key, val);
	}
	return tbl;
    }
}
