/* Generated By:JJTree: Do not edit this line. ASTIfExpression.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTIfExpression extends SimpleNode {
    public ASTIfExpression(int id) {
	super(id);
    }

    public ASTIfExpression(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	if (Demi.test(((SimpleNode) jjtGetChild(0)).evaluate(demi)))
	    return ((SimpleNode) jjtGetChild(1)).evaluate(demi);
	for (int i = 2; i < jjtGetNumChildren(); i += 2) {
	    SimpleNode node = (SimpleNode) jjtGetChild(i);
	    if (node instanceof ASTExpressionList) {
		return node.evaluate(demi);
	    } else if (Demi.test(node.evaluate(demi))) {
		return ((SimpleNode) jjtGetChild(i + 1)).evaluate(demi);
	    }
	}
	return null;
    }
}
