/* Generated By:JJTree: Do not edit this line. ASTInstanceOfNode.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTInstanceOfNode extends SimpleNode {
    public ASTInstanceOfNode(int id) {
	super(id);
    }

    public ASTInstanceOfNode(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	Object obj = ((SimpleNode) jjtGetChild(0)).evaluate(demi);
	if (obj == null) {
	    return Boolean.FALSE;
	}
	Object cls = ((SimpleNode) jjtGetChild(1)).evaluate(demi);
	if (cls == null || !(cls instanceof Class))
	    throw new IllegalTypeException(cls, "Class");
	return new Boolean(((Class) cls).isInstance(obj));
    }
}
