/* Generated By:JJTree: Do not edit this line. ASTIntegerLiteral.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTIntegerLiteral extends LiteralNode {
  public ASTIntegerLiteral(int id) {
    super(id);
  }

  public ASTIntegerLiteral(Parser p, int id) {
    super(p, id);
  }

}
