/* Generated By:JJTree: Do not edit this line. ASTIdentityEqualNode.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTIdentityEqualNode extends SimpleNode {
    public ASTIdentityEqualNode(int id) {
	super(id);
    }

    public ASTIdentityEqualNode(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	Object left = ((SimpleNode) jjtGetChild(0)).evaluate(demi);
	Object right = ((SimpleNode) jjtGetChild(1)).evaluate(demi);
	return new Boolean(left == right);
    }
}
