/* Generated By:JJTree: Do not edit this line. ASTLShiftAssign.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTLShiftAssign extends ASTLShiftNode {
    public ASTLShiftAssign(int id) {
	super(id);
    }

    public ASTLShiftAssign(Parser p, int id) {
	super(p, id);
    }

    public static Node jjtCreate(int id) {
	return new ASTLShiftAssign(id);
    }

    public static Node jjtCreate(Parser p, int id) {
	return new ASTLShiftAssign(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	SimpleNode lhs = (SimpleNode) jjtGetChild(0);
	Object val = super.evaluate(demi);
	return assign(demi, lhs, val);
    }
}
