/* Generated By:JJTree: Do not edit this line. ASTLessThanNode.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTLessThanNode extends SimpleNode {
    public ASTLessThanNode(int id) {
	super(id);
    }

    public ASTLessThanNode(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	Object left = ((SimpleNode) jjtGetChild(0)).evaluate(demi);
	Object right = ((SimpleNode) jjtGetChild(1)).evaluate(demi);
	if (left instanceof Number && right instanceof Number)
	    return new Boolean(Numeric.compare((Number) left,
					       (Number) right) < 0);
	throw new IllegalArgumentException("illegal arguments " +
					   left + ", " + right +
					   " for <");
    }
}
