/* Generated By:JJTree: Do not edit this line. ASTMemberAccess.java */

package JP.ac.osaka_u.shugo.demi;

import java.lang.reflect.*;

public class ASTMemberAccess extends SimpleNode {

    Symbol symbol;

    public ASTMemberAccess(int id) {
	super(id);
    }

    public ASTMemberAccess(Parser p, int id) {
	super(p, id);
    }

    public String getName() {
	return symbol.getName();
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	String name = symbol.getName();
	Object obj = ((SimpleNode) jjtGetChild(0)).evaluate(demi);
	if (obj.getClass().isArray() && name.equals("length")) {
	    return new Integer(Array.getLength(obj));
	} else {
	    try {
		Field field = obj.getClass().getField(name);
		return field.get(obj);
	    } catch (NoSuchFieldException e) {
		String msg = "no such field " + name +
		    " for " + obj.getClass().getName();
		throw new NoSuchFieldException(msg);
	    }
	}
    }
}
