/* Generated By:JJTree: Do not edit this line. ASTMulAssign.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTMulAssign extends ASTMulNode {
    public ASTMulAssign(int id) {
	super(id);
    }

    public ASTMulAssign(Parser p, int id) {
	super(p, id);
    }

    public static Node jjtCreate(int id) {
	return new ASTMulAssign(id);
    }

    public static Node jjtCreate(Parser p, int id) {
	return new ASTMulAssign(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	SimpleNode lhs = (SimpleNode) jjtGetChild(0);
	Object val = super.evaluate(demi);
	return assign(demi, lhs, val);
    }
}
