/* Generated By:JJTree: Do not edit this line. ASTNullLiteral.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTNullLiteral extends SimpleNode {
    public ASTNullLiteral(int id) {
	super(id);
    }

    public ASTNullLiteral(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) {
	return null;
    }
}
