/* Generated By:JJTree: Do not edit this line. ASTNotNode.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTNotNode extends SimpleNode {
    public ASTNotNode(int id) {
	super(id);
    }
    
    public ASTNotNode(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	Object obj = ((SimpleNode) jjtGetChild(0)).evaluate(demi);
	return new Boolean(!Demi.test(obj));
    }
}
