/* Generated By:JJTree: Do not edit this line. ASTOrAssign.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTOrAssign extends ASTBitwiseOrNode {
    public ASTOrAssign(int id) {
	super(id);
    }

    public ASTOrAssign(Parser p, int id) {
	super(p, id);
    }

    public static Node jjtCreate(int id) {
	return new ASTOrAssign(id);
    }

    public static Node jjtCreate(Parser p, int id) {
	return new ASTOrAssign(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	SimpleNode lhs = (SimpleNode) jjtGetChild(0);
	Object val = super.evaluate(demi);
	return assign(demi, lhs, val);
    }
}
