/* Generated By:JJTree: Do not edit this line. ASTPrimarySuffix.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTPrimarySuffix extends SimpleNode {
  public ASTPrimarySuffix(int id) {
    super(id);
  }

  public ASTPrimarySuffix(Parser p, int id) {
    super(p, id);
  }

}
