/* Generated By:JJTree: Do not edit this line. ASTRUShiftAssign.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTRUShiftAssign extends ASTRUnsignedShiftNode {
    public ASTRUShiftAssign(int id) {
	super(id);
    }

    public ASTRUShiftAssign(Parser p, int id) {
	super(p, id);
    }

    public static Node jjtCreate(int id) {
	return new ASTRUShiftAssign(id);
    }

    public static Node jjtCreate(Parser p, int id) {
	return new ASTRUShiftAssign(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	SimpleNode lhs = (SimpleNode) jjtGetChild(0);
	Object val = super.evaluate(demi);
	return assign(demi, lhs, val);
    }
}
