/* Generated By:JJTree: Do not edit this line. ASTRShiftAssign.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTRShiftAssign extends ASTRSignedShiftNode {
    public ASTRShiftAssign(int id) {
	super(id);
    }

    public ASTRShiftAssign(Parser p, int id) {
	super(p, id);
    }

    public static Node jjtCreate(int id) {
	return new ASTRShiftAssign(id);
    }

    public static Node jjtCreate(Parser p, int id) {
	return new ASTRShiftAssign(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	SimpleNode lhs = (SimpleNode) jjtGetChild(0);
	Object val = super.evaluate(demi);
	return assign(demi, lhs, val);
    }
}
