/* Generated By:JJTree: Do not edit this line. ASTSymbol.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTSymbol extends SimpleNode {

    Symbol symbol;

    public ASTSymbol(int id) {
	super(id);
    }

    public ASTSymbol(Parser p, int id) {
	super(p, id);
    }

    public static Node jjtCreate(int id) {
	return new ASTSymbol(id);
    }

    public static Node jjtCreate(Parser p, int id) {
	return new ASTSymbol(p, id);
    }

    protected Object evaluate0(Demi demi) {
	return symbol;
    }
}
