/* Generated By:JJTree: Do not edit this line. ASTSynchronizedExpression.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTSynchronizedExpression extends SimpleNode {
    public ASTSynchronizedExpression(int id) {
	super(id);
    }

    public ASTSynchronizedExpression(Parser p, int id) {
	super(p, id);
    }

    public static Node jjtCreate(int id) {
	return new ASTSynchronizedExpression(id);
    }

    public static Node jjtCreate(Parser p, int id) {
	return new ASTSynchronizedExpression(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	Object obj = ((SimpleNode) jjtGetChild(0)).evaluate(demi);
	synchronized (obj) {
	    return ((SimpleNode) jjtGetChild(1)).evaluate(demi);
	}
    }
}
