/* Generated By:JJTree: Do not edit this line. ASTSubNode.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTSubNode extends SimpleNode {
    public ASTSubNode(int id) {
	super(id);
    }

    public ASTSubNode(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	Object left = ((SimpleNode) jjtGetChild(0)).evaluate(demi);
	Object right = ((SimpleNode) jjtGetChild(1)).evaluate(demi);
	if (left instanceof Number && right instanceof Number)
	    return Numeric.subtract((Number) left, (Number) right);
	throw new IllegalArgumentException("illegal arguments " +
					   left + ", " + right +
					   " for -");
    }
}
