/* Generated By:JJTree: Do not edit this line. ASTStringLiteral.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTStringLiteral extends LiteralNode {
  public ASTStringLiteral(int id) {
    super(id);
  }

  public ASTStringLiteral(Parser p, int id) {
    super(p, id);
  }

}
