/* Generated By:JJTree: Do not edit this line. ASTSubAssign.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTSubAssign extends ASTSubNode {
    public ASTSubAssign(int id) {
	super(id);
    }

    public ASTSubAssign(Parser p, int id) {
	super(p, id);
    }

    public static Node jjtCreate(int id) {
	return new ASTSubAssign(id);
    }

    public static Node jjtCreate(Parser p, int id) {
	return new ASTSubAssign(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	SimpleNode lhs = (SimpleNode) jjtGetChild(0);
	Object val = super.evaluate(demi);
	return assign(demi, lhs, val);
    }
}
