/* Generated By:JJTree: Do not edit this line. ASTThrow.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTThrow extends SimpleNode {
    public ASTThrow(int id) {
	super(id);
    }

    public ASTThrow(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	Object obj = ((SimpleNode) jjtGetChild(0)).evaluate(demi);
	if (obj instanceof Throwable) {
	    throw (Throwable) obj;
	} else if (obj instanceof String) {
	    throw new RuntimeException((String) obj);
	} else {
	    throw new IllegalTypeException(obj, "Throwable");
	}
    }
}
