/* Generated By:JJTree: Do not edit this line. ASTThis.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTThis extends SimpleNode {
    public ASTThis(int id) {
	super(id);
    }

    public ASTThis(Parser p, int id) {
	super(p, id);
    }

    public static Node jjtCreate(int id) {
	return new ASTThis(id);
    }

    public static Node jjtCreate(Parser p, int id) {
	return new ASTThis(p, id);
    }

    protected Object evaluate0(Demi demi) {
	return demi.getScope().module;
    }
}
