/* Generated By:JJTree: Do not edit this line. ASTUnaryMinusNode.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTUnaryMinusNode extends SimpleNode {
    public ASTUnaryMinusNode(int id) {
	super(id);
    }

    public ASTUnaryMinusNode(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	Object obj = ((SimpleNode) jjtGetChild(0)).evaluate(demi);
	if (obj instanceof Number)
	    return Numeric.negate((Number) obj);
	throw new IllegalArgumentException(
			 "illegal argument " + obj + " for -");
    }
}
