/* Generated By:JJTree: Do not edit this line. ASTVectorExpression.java */

package JP.ac.osaka_u.shugo.demi;

import java.util.Vector;

public class ASTVectorExpression extends SimpleNode {
    public ASTVectorExpression(int id) {
	super(id);
    }

    public ASTVectorExpression(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	Vector v = new Vector(jjtGetNumChildren());
	for (int i = 0; i < jjtGetNumChildren(); i++) {
	    Object val = ((SimpleNode) jjtGetChild(i)).evaluate(demi);
	    v.addElement(val);
	}
	return v;
    }
}
