/* Generated By:JJTree: Do not edit this line. ASTVariable.java */

package JP.ac.osaka_u.shugo.demi;

import java.util.*;

public class ASTVariable extends SimpleNode {

    Symbol symbol;

    public ASTVariable(int id) {
	super(id);
    }
    
    public ASTVariable(Parser p, int id) {
	super(p, id);
    }

    protected Object evaluate0(Demi demi) {
	Scope scope = demi.getScope();
	try {
	    return scope.getVariable(symbol);
	} catch (NameError e) {
	    String className = symbol.getName();
	    try {
		return Class.forName(className);
	    } catch (ClassNotFoundException cnf) {
	    }
	    for (int i = demi.importedPackages.size() - 1; i >= 0; i--) {
		String pkgName = (String) demi.importedPackages.elementAt(i);
		try {
		    return Class.forName(pkgName + "." + className);
		} catch (ClassNotFoundException cnf) {
		}
	    }
	}
	throw new NameError(symbol);
    }
}
