/* Generated By:JJTree: Do not edit this line. ASTXorAssign.java */

package JP.ac.osaka_u.shugo.demi;

public class ASTXorAssign extends ASTBitwiseXorNode {
    public ASTXorAssign(int id) {
	super(id);
    }

    public ASTXorAssign(Parser p, int id) {
	super(p, id);
    }

    public static Node jjtCreate(int id) {
	return new ASTXorAssign(id);
    }

    public static Node jjtCreate(Parser p, int id) {
	return new ASTXorAssign(p, id);
    }

    protected Object evaluate0(Demi demi) throws Throwable {
	SimpleNode lhs = (SimpleNode) jjtGetChild(0);
	Object val = super.evaluate(demi);
	return assign(demi, lhs, val);
    }
}
